name: 'git-issue-release'
description: 'Automatically generate PRs diff from previous release'
inputs:
  release-tag-pattern:
    description: "Pattern of release tag written in regex. It is used to link GitHub Releases and release Issues (find latest release or find issue to close after release is published)"
    required: true
    default: '^v'
  release-label:
    description: 'Label of release issue (comma separated if there are multiple)'
    required: true
    default: 'release'
  release-issue-title:
    description: 'Issue title for release issue'
    required: true
    default: "What's changed in the next release"
  release-issue-title-published:
    description: 'Issue title after published'
    required: true
    default: "Release: :tag_name: is released!"
  description:
    description: "Additional description for release issue"
    required: false
    default: ""
  description-file-path:
    description: "The file path in the repository for an additional description for release issue"
    required: false
    default: ""
  configuration-file-path:
    description: "Specifies a path to a file in the repository containing configuration settings used for generating the release notes."
    required: false
    default: ""
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'  
  color: 'green'
